#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
spring:
  application:
    name: care-management
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
  security:
    oauth2:
      client:
        registration:
          operaton:
            authorization-grant-type: client_credentials
            provider: operaton
#========================================
# Integration settings
#========================================
integration:
  operaton:
    connect-timeout: 5
    read-timeout: 30
