SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE attachment;
TRUNCATE TABLE attachment_data;
TRUNCATE TABLE contact_channel;
TRUNCATE TABLE decision;
TRUNCATE TABLE errand_document;
-- The access log was missing here: every AppTest request writes rows to it, so without this they accumulate across
-- ITs. Harmless while nothing asserted on them; not harmless now that a search writes one row per hit.
TRUNCATE TABLE errand_co_caseworker;
TRUNCATE TABLE errand_event;
TRUNCATE TABLE errand_financial_assistance;
TRUNCATE TABLE errand_financial_assistance_calculation_draft;
TRUNCATE TABLE errand_financial_assistance_monitoring;
TRUNCATE TABLE errand_financial_assistance_section_approval;
TRUNCATE TABLE errand_financial_assistance_warning;
TRUNCATE TABLE errand_form_snapshot;
TRUNCATE TABLE errand_message;
TRUNCATE TABLE errand_note;
TRUNCATE TABLE errand_status_history;
TRUNCATE TABLE message_attachment;
TRUNCATE TABLE message_attachment_data;
TRUNCATE TABLE message_read_receipt;
TRUNCATE TABLE notification;
TRUNCATE TABLE stakeholder;
TRUNCATE TABLE errand;
TRUNCATE TABLE errand_number_sequence;
TRUNCATE TABLE lookup;
TRUNCATE TABLE namespace_config;
TRUNCATE TABLE shedlock;
SET FOREIGN_KEY_CHECKS = 1;
