SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE attachment;
TRUNCATE TABLE attachment_data;
TRUNCATE TABLE contact_channel;
TRUNCATE TABLE decision;
TRUNCATE TABLE errand_document;
TRUNCATE TABLE errand_financial_assistance;
TRUNCATE TABLE errand_message;
TRUNCATE TABLE errand_note;
TRUNCATE TABLE errand_status_history;
TRUNCATE TABLE message_attachment;
TRUNCATE TABLE message_attachment_data;
TRUNCATE TABLE message_read_receipt;
TRUNCATE TABLE notification;
TRUNCATE TABLE stakeholder;
TRUNCATE TABLE errand;
TRUNCATE TABLE errand_number_sequence;
TRUNCATE TABLE lookup;
TRUNCATE TABLE namespace_config;
TRUNCATE TABLE shedlock;
SET FOREIGN_KEY_CHECKS = 1;
