-- Consolidated baseline schema for api-service-caremanagement.
-- Squashed from the original V1_0..V5_33 migration series (no live DB to preserve — the
-- deployable envs are wiped and re-created from this single baseline). Generated by applying
-- the full historical series to a clean MariaDB 10.6 and dumping the resulting structure,
-- then: dropping redundant errand indexes, sizing UUID id/FK columns at varchar(36), and
-- dropping the historical lookup seed data (the canonical copy ships in code via
-- ErrandTypeContribution; the lookup rows are a runtime-editable mirror created on demand).

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `attachment` (
  `attachment_data_id` int(11) NOT NULL,
  `file_size` int(11) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `errand_id` varchar(36) NOT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `id` varchar(36) NOT NULL,
  `mime_type` varchar(128) DEFAULT NULL,
  `municipality_id` varchar(8) DEFAULT NULL,
  `namespace` varchar(32) DEFAULT NULL,
  `origin` varchar(32) DEFAULT NULL,
  `sender_role` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_attachment_data_id` (`attachment_data_id`),
  KEY `idx_attachment_file_name` (`file_name`),
  KEY `idx_attachment_municipality_id` (`municipality_id`),
  KEY `idx_attachment_namespace` (`namespace`),
  KEY `fk_errand_attachment_errand_id` (`errand_id`),
  CONSTRAINT `fk_attachment_data_attachment` FOREIGN KEY (`attachment_data_id`) REFERENCES `attachment_data` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `attachment_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `file` longblob DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `contact_channel` (
  `stakeholder_id` varchar(36) NOT NULL,
  `key` varchar(64) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL,
  KEY `idx_contact_channel_key_value` (`key`,`value`),
  KEY `idx_contact_channel_value` (`value`),
  KEY `fk_stakeholder_contact_channel_stakeholder_id` (`stakeholder_id`),
  CONSTRAINT `fk_stakeholder_contact_channel_stakeholder_id` FOREIGN KEY (`stakeholder_id`) REFERENCES `stakeholder` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `decision` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `decision_type` varchar(32) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL,
  `description` varchar(4096) DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `decision_message` varchar(8192) DEFAULT NULL,
  `decision_date` date DEFAULT NULL,
  `period_from` date DEFAULT NULL,
  `period_to` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_decision_errand_id` (`errand_id`),
  KEY `idx_decision_decision_type` (`decision_type`),
  KEY `idx_decision_errand_id_created` (`errand_id`,`created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand` (
  `created` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `touched` datetime(6) DEFAULT NULL,
  `assigned_user_id` varchar(64) DEFAULT NULL,
  `id` varchar(36) NOT NULL,
  `municipality_id` varchar(8) NOT NULL,
  `namespace` varchar(32) NOT NULL,
  `priority` varchar(16) DEFAULT NULL,
  `reporter_user_id` varchar(64) DEFAULT NULL,
  `status` varchar(64) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `type_slug` varchar(64) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `process_definition_name` varchar(128) DEFAULT NULL,
  `process_instance_id` varchar(255) DEFAULT NULL,
  `errand_number` varchar(64) DEFAULT NULL,
  `applicant_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_errand_errand_number` (`errand_number`),
  KEY `idx_errand_namespace` (`namespace`),
  KEY `idx_errand_municipality_namespace_type_slug` (`municipality_id`,`namespace`,`type_slug`),
  KEY `idx_errand_municipality_namespace_status` (`municipality_id`,`namespace`,`status`),
  KEY `idx_errand_municipality_namespace_assigned_user_id` (`municipality_id`,`namespace`,`assigned_user_id`),
  KEY `idx_errand_municipality_namespace_reporter_user_id` (`municipality_id`,`namespace`,`reporter_user_id`),
  KEY `idx_errand_municipality_namespace_status_touched` (`municipality_id`,`namespace`,`status`,`touched`),
  KEY `idx_errand_municipality_namespace_created` (`municipality_id`,`namespace`,`created`),
  KEY `idx_errand_municipality_namespace_touched` (`municipality_id`,`namespace`,`touched`),
  KEY `idx_errand_municipality_namespace_applicant_name` (`municipality_id`,`namespace`,`applicant_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_document` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `document_type` varchar(255) NOT NULL,
  `heading` varchar(255) NOT NULL,
  `document_text` longtext DEFAULT NULL,
  `document_date` date NOT NULL,
  `document_time` time DEFAULT NULL,
  `status` varchar(16) NOT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `created` datetime(6) NOT NULL,
  `modified_by` varchar(64) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `locked_by` varchar(64) DEFAULT NULL,
  `locked` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_document_errand_id` (`errand_id`),
  KEY `idx_document_document_date` (`document_date`),
  CONSTRAINT `fk_document_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_event` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `municipality_id` varchar(16) NOT NULL,
  `namespace` varchar(64) NOT NULL,
  `action` varchar(16) NOT NULL,
  `target` varchar(255) NOT NULL,
  `description` varchar(512) DEFAULT NULL,
  `http_method` varchar(8) DEFAULT NULL,
  `request_path` varchar(1024) DEFAULT NULL,
  `actor` varchar(64) DEFAULT NULL,
  `actor_type` varchar(32) DEFAULT NULL,
  `request_id` varchar(64) DEFAULT NULL,
  `status_code` int(11) DEFAULT NULL,
  `created` datetime(6) NOT NULL,
  `source` varchar(16) NOT NULL DEFAULT 'HTTP',
  PRIMARY KEY (`id`),
  KEY `idx_errand_event_errand_id` (`errand_id`),
  KEY `idx_errand_event_errand_id_created` (`errand_id`,`created`),
  KEY `idx_errand_event_created` (`created`),
  KEY `idx_errand_event_source` (`source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_asset` (
  `errand_id` varchar(36) NOT NULL,
  `asset_category` varchar(64) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `value` decimal(12,2) DEFAULT NULL,
  `property_type` varchar(64) DEFAULT NULL,
  `purchase_year` int(11) DEFAULT NULL,
  `purchase_price` decimal(12,2) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `company_asset_sum` decimal(12,2) DEFAULT NULL,
  `vehicle_type` varchar(64) DEFAULT NULL,
  `registration_number` varchar(16) DEFAULT NULL,
  `purchase_date` date DEFAULT NULL,
  KEY `idx_fa_asset_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_asset_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_calculation_draft_norm_type` (
  `errand_id` varchar(36) NOT NULL,
  `norm_type` varchar(32) DEFAULT NULL,
  KEY `idx_fa_calc_draft_norm_type_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_calc_draft_norm_type_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance_calculation_draft` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_child` (
  `errand_id` varchar(36) NOT NULL,
  `party_id` varchar(36) DEFAULT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `school_name` varchar(255) DEFAULT NULL,
  `residence_extent` varchar(32) DEFAULT NULL,
  `days_in_home` int(11) DEFAULT NULL,
  KEY `idx_fa_child_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_child_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_cost` (
  `errand_id` varchar(36) NOT NULL,
  `cost_type` varchar(64) DEFAULT NULL,
  `applied_amount` decimal(12,2) DEFAULT NULL,
  `other_sub_type` varchar(64) DEFAULT NULL,
  `specification` longtext DEFAULT NULL,
  `recipient_or_period` longtext DEFAULT NULL,
  KEY `idx_fa_cost_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_cost_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_income` (
  `errand_id` varchar(36) NOT NULL,
  `income_type` varchar(64) DEFAULT NULL,
  `amount` decimal(12,2) DEFAULT NULL,
  `income_date` date DEFAULT NULL,
  `recipient` varchar(32) DEFAULT NULL,
  KEY `idx_fa_income_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_income_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_job_application` (
  `errand_id` varchar(36) NOT NULL,
  `person` varchar(255) DEFAULT NULL,
  `application_date` date DEFAULT NULL,
  `job_title` varchar(255) DEFAULT NULL,
  `employer_and_place` varchar(255) DEFAULT NULL,
  KEY `idx_fa_job_application_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_job_application_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_norm_expense` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `origin` varchar(16) NOT NULL,
  `cost_type` varchar(64) NOT NULL,
  `other_sub_type` varchar(32) DEFAULT NULL,
  `specification` longtext DEFAULT NULL,
  `applied_amount` decimal(12,2) DEFAULT NULL,
  `process_amount` decimal(12,2) DEFAULT NULL,
  `caseworker_amount` decimal(12,2) DEFAULT NULL,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `note` longtext DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `updated` datetime(6) DEFAULT NULL,
  `bucket` varchar(20) NOT NULL DEFAULT 'EXPENSE',
  `position` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fa_norm_expense_errand` (`errand_id`),
  CONSTRAINT `fk_fa_norm_expense_draft` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance_calculation_draft` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_norm_income` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `origin` varchar(16) NOT NULL,
  `type_id` int(11) DEFAULT NULL,
  `type_name` varchar(255) DEFAULT NULL,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `note` longtext DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `updated` datetime(6) DEFAULT NULL,
  `applicant_process_amount` decimal(12,2) DEFAULT NULL,
  `applicant_caseworker_amount` decimal(12,2) DEFAULT NULL,
  `applicant_amount_date` datetime(6) DEFAULT NULL,
  `coapplicant_process_amount` decimal(12,2) DEFAULT NULL,
  `coapplicant_caseworker_amount` decimal(12,2) DEFAULT NULL,
  `coapplicant_amount_date` datetime(6) DEFAULT NULL,
  `position` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fa_norm_income_errand` (`errand_id`),
  CONSTRAINT `fk_fa_norm_income_draft` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance_calculation_draft` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_norm_person` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `origin` varchar(16) NOT NULL,
  `party_id` varchar(36) DEFAULT NULL,
  `role` varchar(16) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `process_days` int(11) DEFAULT NULL,
  `caseworker_days` int(11) DEFAULT NULL,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `note` longtext DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `updated` datetime(6) DEFAULT NULL,
  `included` bit(1) NOT NULL DEFAULT b'1',
  `deviation_from_date` date DEFAULT NULL,
  `deviation_to_date` date DEFAULT NULL,
  `norm_interval` varchar(64) DEFAULT NULL,
  `job_stimulus_amount` decimal(12,2) DEFAULT NULL,
  `position` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fa_norm_person_errand` (`errand_id`),
  CONSTRAINT `fk_fa_norm_person_draft` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance_calculation_draft` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_norm_type` (
  `errand_id` varchar(36) NOT NULL,
  `norm_type` varchar(32) DEFAULT NULL,
  KEY `idx_fa_norm_type_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_norm_type_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_pending_benefit` (
  `errand_id` varchar(36) NOT NULL,
  `benefit_name` varchar(255) DEFAULT NULL,
  `applicant_name` varchar(255) DEFAULT NULL,
  KEY `idx_fa_pending_benefit_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_pending_benefit_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_person` (
  `errand_id` varchar(36) NOT NULL,
  `role` varchar(64) DEFAULT NULL,
  `party_id` varchar(36) DEFAULT NULL,
  `needs_interpreter` bit(1) DEFAULT NULL,
  `interpreter_language` varchar(64) DEFAULT NULL,
  `had_work_last12_months` bit(1) DEFAULT NULL,
  `had_work_description` longtext DEFAULT NULL,
  `payment_method` varchar(32) DEFAULT NULL,
  `clearing_number` varchar(16) DEFAULT NULL,
  `account_number` varchar(32) DEFAULT NULL,
  `other_payment_description` longtext DEFAULT NULL,
  `payment_same_as_previous` bit(1) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `notify_by_email` bit(1) DEFAULT NULL,
  `notify_by_sms` bit(1) DEFAULT NULL,
  KEY `idx_fa_person_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_person_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_planned_activity` (
  `errand_id` varchar(36) NOT NULL,
  `person` varchar(255) DEFAULT NULL,
  `activity` longtext DEFAULT NULL,
  `period_from` date DEFAULT NULL,
  `period_to` date DEFAULT NULL,
  KEY `idx_fa_planned_activity_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_planned_activity_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_fa_planning` (
  `errand_id` varchar(36) NOT NULL,
  `person` varchar(255) DEFAULT NULL,
  `planning_type` varchar(64) DEFAULT NULL,
  `work_extent` varchar(32) DEFAULT NULL,
  `work_description` longtext DEFAULT NULL,
  `sick_leave_level` varchar(32) DEFAULT NULL,
  `sfi_study_path` varchar(64) DEFAULT NULL,
  `sfi_course` varchar(64) DEFAULT NULL,
  `other_description` longtext DEFAULT NULL,
  KEY `idx_fa_planning_errand_id` (`errand_id`),
  CONSTRAINT `fk_fa_planning_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand_financial_assistance` (`errand_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_financial_assistance` (
  `errand_id` varchar(36) NOT NULL,
  `application_type` varchar(32) DEFAULT NULL,
  `marital_status` varchar(32) DEFAULT NULL,
  `period_month` int(11) DEFAULT NULL,
  `period_year` int(11) DEFAULT NULL,
  `period_choice` varchar(32) DEFAULT NULL,
  `other_benefit_description` longtext DEFAULT NULL,
  `livelihood_description` longtext DEFAULT NULL,
  `has_children_under21` bit(1) DEFAULT NULL,
  `children_residence_changed` bit(1) DEFAULT NULL,
  `children_residence_change_description` longtext DEFAULT NULL,
  `housing_form` varchar(32) DEFAULT NULL,
  `housing_rooms_plus_kitchen` int(11) DEFAULT NULL,
  `housing_description` longtext DEFAULT NULL,
  `housing_changed` bit(1) DEFAULT NULL,
  `housing_change_description` longtext DEFAULT NULL,
  `has_incomes` bit(1) DEFAULT NULL,
  `has_pending_benefits` bit(1) DEFAULT NULL,
  `has_assets` bit(1) DEFAULT NULL,
  `stays_in_municipality` bit(1) DEFAULT NULL,
  `stay_description` longtext DEFAULT NULL,
  `attestation` bit(1) DEFAULT NULL,
  `attested_at` datetime(6) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `housing_person_count` int(11) DEFAULT NULL,
  `last_daily_run_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`errand_id`),
  CONSTRAINT `fk_financial_assistance_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_financial_assistance_calculation_draft` (
  `errand_id` varchar(36) NOT NULL,
  `application_month` varchar(7) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `updated` datetime(6) DEFAULT NULL,
  `norm_id` int(11) DEFAULT NULL,
  `calculation_from_date` date DEFAULT NULL,
  `calculation_to_date` date DEFAULT NULL,
  `calculation_date` date DEFAULT NULL,
  `has_custom_household_size` bit(1) DEFAULT NULL,
  `household_size` int(11) DEFAULT NULL,
  PRIMARY KEY (`errand_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_financial_assistance_monitoring` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` longtext DEFAULT NULL,
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `updated` datetime(6) DEFAULT NULL,
  `source` varchar(16) NOT NULL DEFAULT 'CASEWORKER',
  `lifecare_id` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fa_monitoring_errand` (`errand_id`),
  KEY `idx_fa_monitoring_lifecare` (`errand_id`,`lifecare_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_financial_assistance_section_approval` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `section` varchar(32) NOT NULL,
  `approved` bit(1) NOT NULL DEFAULT b'0',
  `approved_by` varchar(64) DEFAULT NULL,
  `approved_at` datetime(6) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `updated` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_fa_section_approval` (`errand_id`,`section`),
  KEY `idx_fa_section_approval_errand` (`errand_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_financial_assistance_warning` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `type` varchar(64) NOT NULL,
  `source_key` varchar(255) DEFAULT NULL,
  `message` longtext DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `auto_resolved` bit(1) NOT NULL DEFAULT b'0',
  `created` datetime(6) DEFAULT NULL,
  `updated` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fa_warning_errand` (`errand_id`),
  KEY `idx_fa_warning_dedup` (`errand_id`,`type`,`source_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_form_snapshot` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `municipality_id` varchar(32) NOT NULL,
  `namespace` varchar(128) NOT NULL,
  `type_slug` varchar(64) NOT NULL,
  `schema_version` varchar(32) NOT NULL,
  `form_definition_version` varchar(64) DEFAULT NULL,
  `locale` varchar(16) DEFAULT NULL,
  `content_hash` char(64) NOT NULL,
  `payload` longtext NOT NULL,
  `captured_at` datetime(6) DEFAULT NULL,
  `created` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_form_snapshot_errand` (`errand_id`),
  KEY `idx_form_snapshot_errand_id` (`errand_id`),
  CONSTRAINT `fk_form_snapshot_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_journal_entry` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `entry_type` varchar(255) NOT NULL,
  `heading` varchar(255) NOT NULL,
  `entry_text` longtext DEFAULT NULL,
  `entry_date` date NOT NULL,
  `entry_time` time DEFAULT NULL,
  `status` varchar(16) NOT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `created` datetime(6) NOT NULL,
  `modified_by` varchar(64) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `locked_by` varchar(64) DEFAULT NULL,
  `locked` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_journal_entry_errand_id` (`errand_id`),
  KEY `idx_journal_entry_entry_date` (`entry_date`),
  CONSTRAINT `fk_journal_entry_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_message` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `direction` varchar(16) NOT NULL,
  `body` varchar(8192) NOT NULL,
  `author` varchar(64) DEFAULT NULL,
  `created` datetime(6) NOT NULL,
  `in_reply_to_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_message_errand_id` (`errand_id`),
  KEY `idx_message_created` (`created`),
  KEY `idx_message_in_reply_to_id` (`in_reply_to_id`),
  CONSTRAINT `fk_message_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_message_in_reply_to_id` FOREIGN KEY (`in_reply_to_id`) REFERENCES `errand_message` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_note` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `body` longtext NOT NULL,
  `author` varchar(64) DEFAULT NULL,
  `created` datetime(6) NOT NULL,
  `modified_by` varchar(64) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_note_errand_id` (`errand_id`),
  KEY `idx_note_created` (`created`),
  CONSTRAINT `fk_note_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_number_sequence` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `municipality_id` varchar(8) NOT NULL,
  `namespace` varchar(32) NOT NULL,
  `sequence_year` int(11) NOT NULL,
  `sequence_month` int(11) NOT NULL DEFAULT 0,
  `current_value` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_errand_number_sequence` (`municipality_id`,`namespace`,`sequence_year`,`sequence_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `errand_status_history` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `from_status` varchar(64) DEFAULT NULL,
  `to_status` varchar(64) NOT NULL,
  `changed_by` varchar(64) DEFAULT NULL,
  `changed_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status_history_errand_id` (`errand_id`),
  KEY `idx_status_history_changed_at` (`changed_at`),
  CONSTRAINT `fk_status_history_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `event_publication` (
  `id` binary(16) NOT NULL,
  `listener_id` varchar(255) NOT NULL,
  `event_type` varchar(255) NOT NULL,
  `serialized_event` longtext NOT NULL,
  `publication_date` datetime(6) NOT NULL,
  `completion_date` datetime(6) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `completion_attempts` int(11) DEFAULT NULL,
  `last_resubmission_date` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_event_publication_completion_date` (`completion_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `lookup` (
  `created` datetime(6) DEFAULT NULL,
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `modified` datetime(6) DEFAULT NULL,
  `kind` varchar(32) NOT NULL,
  `name` varchar(255) NOT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `municipality_id` varchar(8) NOT NULL,
  `namespace` varchar(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_lookup_kind_namespace_municipality_id_name` (`kind`,`namespace`,`municipality_id`,`name`),
  KEY `idx_lookup_kind_namespace_municipality_id` (`kind`,`namespace`,`municipality_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `message_attachment` (
  `id` varchar(36) NOT NULL,
  `message_id` varchar(36) NOT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `mime_type` varchar(128) DEFAULT NULL,
  `file_size` int(11) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `sender_role` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_message_attachment_message_id` (`message_id`),
  CONSTRAINT `fk_message_attachment_message_id` FOREIGN KEY (`message_id`) REFERENCES `errand_message` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `message_attachment_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_attachment_id` varchar(36) NOT NULL,
  `file` longblob DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_message_attachment_data_attachment_id` (`message_attachment_id`),
  CONSTRAINT `fk_message_attachment_data_attachment_id` FOREIGN KEY (`message_attachment_id`) REFERENCES `message_attachment` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `message_read_receipt` (
  `id` varchar(36) NOT NULL,
  `message_id` varchar(36) NOT NULL,
  `reader_side` varchar(16) NOT NULL,
  `read_by` varchar(64) DEFAULT NULL,
  `read_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_message_read_receipt_message_side` (`message_id`,`reader_side`),
  KEY `idx_message_read_receipt_message_id` (`message_id`),
  CONSTRAINT `fk_message_read_receipt_message_id` FOREIGN KEY (`message_id`) REFERENCES `errand_message` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `namespace_config` (
  `created` datetime(6) DEFAULT NULL,
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `modified` datetime(6) DEFAULT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `municipality_id` varchar(8) NOT NULL,
  `namespace` varchar(32) NOT NULL,
  `short_code` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_namespace_config_namespace_municipality_id` (`namespace`,`municipality_id`),
  KEY `idx_namespace_config_namespace_municipality_id` (`namespace`,`municipality_id`),
  KEY `idx_namespace_config_municipality_id` (`municipality_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `notification` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `municipality_id` varchar(8) NOT NULL,
  `namespace` varchar(32) NOT NULL,
  `owner_id` varchar(64) DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `sub_type` varchar(32) DEFAULT NULL,
  `description` varchar(512) NOT NULL,
  `content` varchar(2048) DEFAULT NULL,
  `acknowledged` bit(1) NOT NULL DEFAULT b'0',
  `expires` datetime(6) NOT NULL,
  `created` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_notification_errand_id` (`errand_id`),
  KEY `idx_notification_mid_ns_owner_id_acknowledged` (`municipality_id`,`namespace`,`owner_id`,`acknowledged`),
  KEY `idx_notification_mid_ns_errand_id_acknowledged` (`municipality_id`,`namespace`,`errand_id`,`acknowledged`),
  KEY `idx_notification_expires` (`expires`),
  CONSTRAINT `fk_notification_errand_id` FOREIGN KEY (`errand_id`) REFERENCES `errand` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `permit` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `permit_type` varchar(64) DEFAULT NULL,
  `valid_from` date DEFAULT NULL,
  `valid_until` date DEFAULT NULL,
  `conditions` varchar(4096) DEFAULT NULL,
  `status` varchar(32) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_permit_errand_id` (`errand_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `referral` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `authority` varchar(64) DEFAULT NULL,
  `recipient` varchar(32) DEFAULT NULL,
  `sent_at` date DEFAULT NULL,
  `due_at` date DEFAULT NULL,
  `response_text` varchar(4096) DEFAULT NULL,
  `status` varchar(32) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_referral_errand_id` (`errand_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `shedlock` (
  `name` varchar(64) NOT NULL,
  `lock_until` timestamp(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  `locked_at` timestamp(3) NOT NULL DEFAULT current_timestamp(3),
  `locked_by` varchar(64) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stakeholder` (
  `id` varchar(36) NOT NULL,
  `errand_id` varchar(36) NOT NULL,
  `external_id` varchar(255) DEFAULT NULL,
  `external_id_type` varchar(32) DEFAULT NULL,
  `role` varchar(64) DEFAULT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `organization_name` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `care_of` varchar(255) DEFAULT NULL,
  `zip_code` varchar(10) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_stakeholder_external_id_role_errand_id` (`external_id`,`role`,`errand_id`),
  KEY `fk_stakeholder_errand_id` (`errand_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;
